## A blank theme

require(ggplot2)
#require(dplyr)
require(sysfonts) ## for google fonts


new_theme <- theme(complete = FALSE,
      line = element_line(), 
      rect = element_rect(), 
      text = element_text(), 
      title = element_text(), 
      aspect.ratio = 1, 
      axis.title = element_text(), 
      # axis.title.x = element_text(),
      # # axis.title.x.top = element_text(),
      # # axis.title.x.bottom = element_text(),
      # axis.title.y = element_text(), 
      # # axis.title.y.left = element_text(),
      # # axis.title.y.right = element_text(), 
      axis.text = element_text(), 
      # axis.text.x = element_text(), 
      # # axis.text.x.top = element_text(),
      # # axis.text.x.bottom = element_text(), 
      # axis.text.y = element_text(),
      # # axis.text.y.left = element_text(),
      # # axis.text.y.right = element_text(),
      axis.ticks = element_line(), 
      # axis.ticks.x = element_line(), 
      # # axis.ticks.x.top = element_line(), 
      # # axis.ticks.x.bottom = element_line(),
      # axis.ticks.y = element_line(), 
      # # axis.ticks.y.left = element_line(), 
      # # axis.ticks.y.right = element_line(), 
      axis.ticks.length = element_line(),
      axis.line = element_line(), 
      # axis.line.x = element_line(), 
      # # axis.line.x.top = element_line(), 
      # # axis.line.x.bottom = element_line(), 
      # axis.line.y = element_line(),
      # # axis.line.y.left = element_line() = element_line(), 
      # # axis.line.y.right, 
      legend.background = element_rect(), 
      legend.margin = margin(),
      legend.spacing = unit(), 
      # legend.spacing.x, 
      # legend.spacing.y, 
      legend.key = element_rect(),
      legend.key.size = unit(), 
      # legend.key.height = unit(),
      # legend.key.width = unit(), 
      legend.text = element_text(),
      legend.text.align = 0, 
      legend.title = element_text(), 
      legend.title.align = 0, 
      legend.position = "right",
      legend.direction = "vertical", 
      legend.justification = c(.5, .5), 
      legend.box = "vertical", 
      legend.box.just = "left",
      legend.box.margin = margin(), 
      legend.box.background = element_rect(), 
      legend.box.spacing = unit(),
      panel.background - element_rect(), 
      panel.border = element_rect(), 
      panel.spacing = unit(), 
      # panel.spacing.x = unit(),
      # panel.spacing.y = unit(), 
      panel.grid = element_line(), 
      # panel.grid.major = element_line(), 
      # panel.grid.minor = element_line(),
      # # panel.grid.major.x = element_line(), 
      # # panel.grid.major.y = element_line(), 
      # # panel.grid.minor.x = element_line(),
      # # panel.grid.minor.y = element_line(), 
      panel.ontop = FALSE, 
      plot.background = element_rect(), 
      # plot.title = element_text(),
      # plot.subtitle = element_text(), 
      # plot.caption = element_text(), 
      # plot.tag  = element_text(), 
      plot.tag.position = "topleft", 
      plot.margin = unit(),
      strip.background = element_rect(), 
      # strip.background.x = element_rect(), 
      # strip.background.y = element_rect(),
      strip.placement = "inside", 
      strip.text = element_text(), 
      # strip.text.x = element_text(), 
      # strip.text.y = element_text(),
      # strip.switch.pad.grid = unit(), 
      # strip.switch.pad.wrap = unit(), 
      validate = TRUE)


